Repository ShadowStation/ShadowStation, pull requests merged in 2019-08, with the labels that each got.

#94 [s] Adds donor level command, adds donor ooc chat icon reward
  code/controllers/subsystem/discord.dm
  code/modules/client/preferences.dm
  code/modules/client/verbs/aooc.dm
  code/modules/client/verbs/ooc.dm
  code/modules/discord/accountlink.dm
  code/modules/discord/tgs_commands.dm
  html/templates/header.html
  icons/member_content.dmi
  modular_citadel/code/modules/admin/chat_commands.dm
Labels: Feature, Sprites, Tweak

#96 Proposed Map Changes
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#97 Makes current title screens widescreen by adding black bars
  config/title_screens/images/title1.dmi
  config/title_screens/images/title2.dmi
  config/title_screens/images/wolvesingreyclothing.dmi
Labels: Config Update

#100 Makes the round timer actually work
  code/__HELPERS/time.dm
  code/modules/mob/mob.dm
Labels: Fix

#103 Bar Hotfix
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit

#104 Fixes issue #98 - Sprite error in atmospheric firefighting helmet
  code/modules/clothing/head/hardhat.dm
Labels: Fix

#105 Fixes a bug that allows used/dead face huggers to still infect.
  code/modules/mob/living/carbon/alien/special/facehugger.dm
Labels: Fix

#106 [MIRROR] Resprites RCDs and RPDs
  code/game/objects/items/RPD.dm
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
  icons/obj/tools.dmi
Labels: Feature, Sprites

#102 fuck electrical storms
  modular_shadow/code/modules/events/electrical_storm.dm
  tgstation.dme
Labels: Tweak

#107 Some of the best quotes from our favorite old-school pixel reptile, now as trauma lines!
  strings/traumas.json
Labels: Feature

#110 Adds back sugarcane to megaseed vendors
  code/modules/vending/megaseed.dm
Labels: Fix

#111 Fixes invisible Augment Manipulators
  code/game/machinery/aug_manipulator.dm
Labels: Fix

#112 Fixes wallets turning invisible after inserting IDs
  code/game/objects/items/storage/wallets.dm
Labels: Fix

#114 [MIRROR] Ports "Headset Channel Descriptions Are No Longer Hardcoded"
  code/__DEFINES/radio.dm
  code/__DEFINES/say.dm
  code/datums/saymode.dm
  code/game/communications.dm
  code/game/machinery/bank_machine.dm
  code/game/machinery/cloning.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/borgpanel.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/hivemind.dm
  code/modules/antagonists/changeling/powers/linglink.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_service.dm
  code/modules/jobs/job_types/engineering.dm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/science.dm
  code/modules/jobs/job_types/security.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/mob/living/simple_animal/bot/honkbot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/surgery/organs/vocal_cords.dm
  modular_citadel/code/modules/jobs/job_types/captain.dm
Labels: Code Improvement, Feature, Tweak

#116 removes the head status of the quartermaster and adds autoshotguns to the armory tab
  code/modules/jobs/jobs.dm
  modular_citadel/code/modules/cargo/packs.dm
  modular_citadel/code/modules/jobs/job_types/cargo_service.dm
Labels: Feature, Removal

#118 Ports /tg/'s birthday cake recipe, including caramel
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Feature, Tweak

#121 [s] I'm a smart girl I promise.
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Fix

#122 Ports zero, , null, and empty text strings, all fulfill the ! operator from cit
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Fix, Grammar and Formatting

#125 Ports Podweak race customization
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
Labels: Tweak

#130 Admin revive clears suicide status
  code/modules/mob/living/carbon/carbon.dm
Labels: Administration

#129 Better station ambience drone & preferences label correction
  code/modules/client/preferences.dm
  sound/ambience/shipambience.ogg
Labels: Fix, Sound

#131 Added/removed round start tips.
  strings/sillytips.txt
  strings/tips.txt
Labels: Feature, Removal

#132 Ports syndicate contracts, traitor fixes & refactors, And a bunch of other cool stuff
  code/__DEFINES/antagonists.dm
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/areas.dm
  code/__HELPERS/game.dm
  code/__HELPERS/roundend.dm
  code/__HELPERS/text.dm
  code/_globalvars/lists/poll_ignore.dm
  code/datums/browser.dm
  code/datums/mind.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/pinpointer.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/antagonists/_common/antag_team.dm
  code/modules/antagonists/brother/brother.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/traitor/equipment/contractor.dm
  code/modules/antagonists/traitor/syndicate_contract.dm
  code/modules/cargo/supplypod.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/events/grid_check.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/modular_computers/computers/item/tablet_presets.dm
  code/modules/modular_computers/file_system/programs/antagonist/contract_uplink.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  code/modules/uplink/uplink_items.dm
  html/font-awesome/css/all.min.css
  html/font-awesome/css/v4-shims.min.css
  html/font-awesome/webfonts/fa-brands-400.woff
  html/font-awesome/webfonts/fa-regular-400.eot
  html/font-awesome/webfonts/fa-solid-900.eot
  html/font-awesome/webfonts/fa-solid-900.woff
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/obj/contractor_tablet.dmi
  icons/obj/items_and_weapons.dmi
  modular_citadel/code/datums/uplink_items_cit.dm
  sound/effects/confirmdropoff.ogg
  sound/effects/contractorbatonhit.ogg
  sound/effects/contractstartup.ogg
  sound/effects/podwoosh.ogg
  sound/machines/uplinkerror.ogg
  sound/machines/uplinkpurchase.ogg
  sound/roundend/cj_awshit.ogg
  sound/weapons/contractorbatonextend.ogg
  tgstation.dme
  tgui/assets/tgui.js
  tgui/src/interfaces/synd_contract.ract
Labels: Feature, Refactor, Sound, Sprites, Tweak, UI

#135 Round Time reports the round length from round start, instead of world start
  code/modules/mob/mob.dm
Labels: Tweak

#134 Updates FontAwesome to 5.10.2
  code/modules/client/asset_cache.dm
  code/modules/client/darkmode.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
  code/modules/goonchat/browserassets/css/font-awesome.css
  code/modules/goonchat/browserassets/html/browserOutput.html
  code/modules/tgui/tgui.dm
  html/font-awesome/README.MD
  html/font-awesome/css/all.min.css
  html/font-awesome/webfonts/fa-brands-400.woff
  html/font-awesome/webfonts/fa-regular-400.woff
  modular_citadel/code/datums/uplink_items_cit.dm
  tgui/assets/font-awesome.min.css
  tgui/assets/fonts/SIL-OFL-1.1-LICENSE.md
  tgui/assets/fonts/fontawesome-webfont.eot
  tgui/assets/fonts/fontawesome-webfont.svg
  tgui/assets/fonts/fontawesome-webfont.ttf
  tgui/assets/fonts/fontawesome-webfont.woff
  tgui/assets/fonts/fontawesome-webfont.woff2
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/package.json
  tgui/src/components/titlebar.ract
  tgui/src/components/titlebar.styl
  tgui/src/components/warnings.ract
  tgui/src/tgui.js
Labels: Feature, Removal, UI

#133 Make admins able to adjust and toggle shuttle autocall
  code/controllers/subsystem/shuttle.dm
  code/modules/admin/admin_verbs.dm
  modular_citadel/code/controllers/subsystem/shuttle.dm
  modular_shadow/code/modules/admin/admin.dm
  tgstation.dme
Labels: Feature

#136 Makes Air Alarms Green
  code/modules/atmospherics/machinery/airalarm.dm
  icons/obj/monitors.dmi
Labels: Sprites, Tweak

#138 mag mags can be seen again
  modular_citadel/icons/obj/guns/cit_guns.dmi
Labels: Fix

#137 Adds two new round-end sounds
  code/controllers/subsystem/ticker.dm
  sound/roundend/leavingtg.ogg
  sound/roundend/scrunglartiy.ogg
Labels: Sound

#140 Xeno Queen sprite changes v2
  icons/mob/alienqueen.dmi
Labels: Sprites

#141 [MIRROR] Adds more space ruins.
  _maps/RandomRuins/SpaceRuins/arcade.dmm
  _maps/RandomRuins/SpaceRuins/augmentationfacility.dmm
  _maps/RandomRuins/SpaceRuins/bigape.dmm
  code/datums/ruins/space.dm
  config/spaceRuinBlacklist.txt
Labels: Config Update, Map Edit

#142 [MIRROR] Adds another space ruin
  _maps/RandomRuins/SpaceRuins/spacehermit.dmm
  code/datums/ruins/space.dm
  config/spaceRuinBlacklist.txt
Labels: Config Update, Map Edit

#143 Xeno queen sprite fixes final
  icons/mob/alienqueen.dmi
Labels: Sprites

#145 Ports bamboo and related stuff, adds sugarcane back to the megaseed vendor
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/cargo/packs.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/projectiles/guns/misc/syringe_gun.dm
  code/modules/vending/megaseed.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/hydroponics/equipment.dmi
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  icons/obj/stack_objects.dmi
Labels: Feature, Fix, Sprites

#146 [MIRROR] IC Word filtering
  code/controllers/configuration/configuration.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserassets/js/browserOutput.js
  code/modules/mob/living/say.dm
  config/in_character_filter.txt
Labels: Config Update, Feature

#147 Buffs Poly
  code/modules/mob/living/simple_animal/parrot.dm
  modular_citadel/code/modules/admin/chat_commands.dm
Labels: Feature

#151 Fixes undeleted queries related to the mentor memo system
  modular_citadel/code/modules/mentor/mentor_memo.dm
Labels: Fix

#152 Adds DNR trait
  code/datums/traits/negative.dm
Labels: Feature

#153 Tweaks DNR, and adds DNC trait
  code/__DEFINES/traits.dm
  code/datums/traits/negative.dm
  code/datums/traits/neutral.dm
  code/game/machinery/computer/cloning.dm
  code/game/machinery/exp_cloner.dm
Labels: Feature, Tweak
