Repository ShadowStation/ShadowStation, pull requests merged in 2019-07, with the labels that each got.

#60 Adds clown shoe waddle, waddle dampeners (TM), and other important tweaks
  code/datums/components/footstep.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/mob/living/simple_animal/friendly/penguin.dm
  code/modules/surgery/organs/ears.dm
  tgstation.dme
Labels: Feature, Tweak

#61 Animated speechie bubbles
  icons/mob/talk.dmi
Labels: Sprites

#64 [MIRROR] Match strike sound
  code/game/objects/items/cigs_lighters.dm
  sound/items/match_strike.ogg
Labels: Sound

#63 [MIRROR] Simple animals that are dead have a message on examine.
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#65 Record deaths into game.log
  code/modules/mob/living/carbon/human/death.dm
Labels: Administration

#66 Ports the Quantum Spin Inverter from tg
  code/game/objects/items/devices/swapper.dm
  code/modules/research/designs/bluespace_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/device.dmi
  tgstation.dme
Labels: Feature, Sprites

#67 ID Card Spritse + PDA Painter Rework / modular_shadow
  code/game/machinery/PDApainter.dm
  code/game/machinery/aug_manipulator.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/jobs/job_types/cargo_service.dm
  code/modules/jobs/job_types/civilian.dm
  code/modules/jobs/job_types/engineering.dm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/science.dm
  code/modules/jobs/job_types/security.dm
  icons/obj/pda.dmi
  modular_shadow/README.md
  modular_shadow/code/game/objects/items/cards_ids.dm
  modular_shadow/icons/obj/card.dmi
  modular_shadow/icons/obj/robotics.dmi
  tgstation.dme
Labels: Feature, Fix, Sprites, Tweak

#69 Fixes ShadowBot notify command for the 3rd time
  code/modules/admin/chat_commands.dm
Labels: Fix

#70 Revert "DMAPI Update"
  code/__DEFINES/tgs.config.dm
  code/__DEFINES/tgs.dm
  code/modules/tgs/core/_definitions.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/core/default_event_handler.dm
  code/modules/tgs/core/tgs_version.dm
  code/modules/tgs/includes.dm
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v3210/commands.dm
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v4/commands.dm
Labels: Revert

#71 Revert "Fixes ShadowBot notify command for the 3rd time"
  code/modules/admin/chat_commands.dm
Labels: Revert

#72 [MIRROR] Ports the Chem Master choose your pill PR plus post-improvements
  code/game/objects/items/RPD.dm
  code/modules/client/asset_cache.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/tgui/external.dm
  code/modules/tgui/tgui.dm
  icons/UI_Icons/Pills/pill1.png
  icons/UI_Icons/Pills/pill10.png
  icons/UI_Icons/Pills/pill11.png
  icons/UI_Icons/Pills/pill12.png
  icons/UI_Icons/Pills/pill13.png
  icons/UI_Icons/Pills/pill14.png
  icons/UI_Icons/Pills/pill15.png
  icons/UI_Icons/Pills/pill16.png
  icons/UI_Icons/Pills/pill17.png
  icons/UI_Icons/Pills/pill18.png
  icons/UI_Icons/Pills/pill19.png
  icons/UI_Icons/Pills/pill2.png
  icons/UI_Icons/Pills/pill20.png
  icons/UI_Icons/Pills/pill21.png
  icons/UI_Icons/Pills/pill22.png
  icons/UI_Icons/Pills/pill3.png
  icons/UI_Icons/Pills/pill4.png
  icons/UI_Icons/Pills/pill5.png
  icons/UI_Icons/Pills/pill6.png
  icons/UI_Icons/Pills/pill7.png
  icons/UI_Icons/Pills/pill8.png
  icons/UI_Icons/Pills/pill9.png
  icons/UI_Icons/minesweeper_tiles/eight.png
  icons/UI_Icons/minesweeper_tiles/empty.png
  icons/UI_Icons/minesweeper_tiles/five.png
  icons/UI_Icons/minesweeper_tiles/flag.png
  icons/UI_Icons/minesweeper_tiles/four.png
  icons/UI_Icons/minesweeper_tiles/hidden.png
  icons/UI_Icons/minesweeper_tiles/mine.png
  icons/UI_Icons/minesweeper_tiles/minehit.png
  icons/UI_Icons/minesweeper_tiles/one.png
  icons/UI_Icons/minesweeper_tiles/seven.png
  icons/UI_Icons/minesweeper_tiles/six.png
  icons/UI_Icons/minesweeper_tiles/three.png
  icons/UI_Icons/minesweeper_tiles/two.png
  strings/redpill.json
  tgui/assets/tgui.js
  tgui/src/interfaces/chem_master.ract
  tgui/tgui.html
Labels: Feature, Sprites, UI

#74 [MIRROR] Ports "Makes ventcrawl much easier on the client"
  code/modules/mob/living/ventcrawling.dm
Labels: Fix

#75 [MIRROR] Emitters can be rotated instead of only flipped
  code/modules/power/singularity/emitter.dm
Labels: Fix

#77 Now we can laugh at the first person to die everywhere. Also spelling fixes I guess.
  code/controllers/subsystem/ticker.dm
  code/modules/photography/camera/other.dm
Labels: Feature, Fix

#78 [MIRROR] Ports in the container_type to reagents flags refactor.
  code/__DEFINES/flags.dm
  code/__DEFINES/reagents.dm
  code/_globalvars/bitfields.dm
  code/game/atoms.dm
  code/game/machinery/limbgrower.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/extinguisher.dm
  code/game/objects/items/implants/implant_chem.dm
  code/game/objects/items/tanks/watertank.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/mop_bucket.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/food.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/customizables.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/food_and_drinks/kitchen_machinery/food_cart.dm
  code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/hydroponics/fermenting_barrel.dm
  code/modules/hydroponics/grown/replicapod.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/integrated_electronics/passive/power.dm
  code/modules/integrated_electronics/subtypes/reagents.dm
  code/modules/paperwork/pen.dm
  code/modules/power/cell.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/guns/misc/chem_gun.dm
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/readme.md
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/medspray.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/machinery/circuit_imprinter.dm
  code/modules/research/machinery/departmental_circuit_imprinter.dm
  code/modules/research/machinery/departmental_protolathe.dm
  code/modules/research/machinery/departmental_techfab.dm
  code/modules/research/machinery/protolathe.dm
  code/modules/research/machinery/techfab.dm
  code/modules/research/xenobiology/crossbreeding/__corecross.dm
  code/modules/research/xenobiology/crossbreeding/burning.dm
  code/modules/research/xenobiology/crossbreeding/charged.dm
  code/modules/research/xenobiology/crossbreeding/chilling.dm
  code/modules/research/xenobiology/crossbreeding/industrial.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Refactor

#79 [MIRROR] Ports in Liver removal/failure now also stops passive reagent effects
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/status_procs.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/blob_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#76 [MIRROR] Porting in 18 new drinks from the TGstation, plus tweaking and fixes.
  code/__DEFINES/food.dm
  code/__DEFINES/misc.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/mood_events/food_events.dm
  code/game/turfs/turf.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/hydroponics/grown/root.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/vending/boozeomat.dm
  code/modules/vending/cola.dm
  code/modules/vending/drinnerware.dm
  icons/effects/blood.dmi
  icons/obj/drinks.dmi
  icons/obj/food/containers.dmi
  icons/obj/food/food.dmi
  tgstation.dme
Labels: Feature, Fix, Sprites, Tweak

#80 [MIRROR] Fixes vape and its sprites
  code/game/objects/items/cigs_lighters.dm
  icons/mob/mask.dmi
Labels: Fix, Sprites

#81 [MIRROR] Ports in emoji.dmi updates, plus flushed emoji.
  icons/emoji.dmi
Labels: Feature, Sprites

#82 [MIRROR] Ports in microwave updates and its radial menu.
  code/datums/wires/microwave.dm
  code/game/machinery/_machinery.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  tgstation.dme
Labels: Feature

#83 [MIRROR] ports in "Adds radial menu to arm-mounted implants"
  code/modules/surgery/organs/augments_arms.dm
Labels: Feature

#86 Beepsky Smash requires quadruple sec instead of whiskey because wow
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
Labels: Tweak

#87 BLIIIIIINDED BY THE LIGHT!
  code/__DEFINES/colors.dm
  code/modules/client/darkmode.dm
  code/modules/client/verbs/looc.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
Labels: Tweak

#88 [MIRROR] Fixes a unseen paper work exsplote
  code/modules/cargo/exports/manifest.dm
  code/modules/cargo/order.dm
  code/modules/cargo/packs.dm
  code/modules/crafting/recipes.dm
Labels: Feature, Fix, Tweak

#89 [MIRROR] Peanuts, peanut butter, and PB&J sandwiches.
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/snacks_sandwichtoast.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_sandwich.dm
  code/modules/hydroponics/grown/peanuts.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/vending/megaseed.dm
  icons/obj/food/burgerbread.dmi
  icons/obj/food/containers.dmi
  icons/obj/food/food.dmi
  icons/obj/hydroponics/growing_vegetables.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  tgstation.dme
Labels: Feature, Sprites

#90 [MIRROR] fixes CMO cloak offset and normalize cloak size for the other heads
  icons/mob/neck.dmi
Labels: Sprites

#91 [MIRROR] Adds a reskin option for HoS tenchcoat, the trenchcloak!
  code/modules/clothing/suits/armor.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#92 [MIRROR] Sweaters now cover the groin too
  modular_citadel/code/modules/clothing/under/turtlenecks.dm
Labels: Tweak

#93 Add discord to ckey linking, tweak prefs, add donor chat icon.
  SQL/database_changelog.txt
  SQL/tgstation_schema.sql
  SQL/tgstation_schema_prefixed.sql
  code/__DEFINES/preferences.dm
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/discord.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/preferences.dm
  code/modules/discord/accountlink.dm
  code/modules/discord/manipulation.dm
  code/modules/discord/tgs_commands.dm
  icons/member_content.dmi
  tgstation.dme
Labels: Administration, Config Update, Feature, SQL, Sprites, Tweak
