Repository ShadowStation/ShadowStation, pull requests merged in 2019-09, with the labels that each got.

#155 Atmos tweaks because gassy bois need more things to do.
  code/__DEFINES/reactions.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Balance/Rebalance, Feature, Tweak

#159 Beach and Caves map update
  _maps/RandomZLevels/beach.dmm
  _maps/RandomZLevels/caves.dmm
Labels: Feature, Map Edit, Removal

#165 Kinkmate removals
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#163 Ports Oracle UI Framework
  code/controllers/subsystem/assets.dm
  code/modules/paperwork/paper.dm
  code/modules/recycling/disposal/bin.dm
  modular_shadow/code/modules/oracle_ui/README.md
  modular_shadow/code/modules/oracle_ui/assets.dm
  modular_shadow/code/modules/oracle_ui/hookup_procs.dm
  modular_shadow/code/modules/oracle_ui/oracle_ui.dm
  modular_shadow/code/modules/oracle_ui/themed.dm
  modular_shadow/html/oracle_ui/content/disposal_bin/index.html
  modular_shadow/html/oracle_ui/editor_tool.html
  modular_shadow/html/oracle_ui/themes/nano/index.html
  modular_shadow/html/oracle_ui/themes/nano/sui-nano-common.css
  modular_shadow/html/oracle_ui/themes/nano/sui-nano-common.js
  modular_shadow/html/oracle_ui/themes/nano/sui-nano-jquery.min.js
  tgstation.dme
Labels: Feature, Refactor

#168 Many hydro plant fixes
  code/modules/hydroponics/grown/cereals.dm
  code/modules/hydroponics/grown/corn.dm
  code/modules/hydroponics/grown/flowers.dm
  code/modules/hydroponics/grown/mushrooms.dm
  code/modules/hydroponics/grown/pineapple.dm
  code/modules/hydroponics/grown/tea_coffee.dm
Labels: Feature, Removal, Tweak

#166 Gas miners in atmos tanks
  _maps/kilostation.dm
  _maps/kilostation.json
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/arrival_kilo.dmm
  _maps/shuttles/cargo_kilo.dmm
  _maps/shuttles/emergency_kilo.dmm
  _maps/shuttles/ferry_kilo.dmm
  _maps/shuttles/labour_kilo.dmm
  _maps/shuttles/mining_kilo.dmm
  code/datums/map_config.dm
  code/datums/shuttles.dm
  code/game/area/Space_Station_13_areas.dm
  icons/turf/areas.dmi
Labels: Map Edit, Sprites

#170 Revert "Gas miners in atmos tanks"
  _maps/kilostation.dm
  _maps/kilostation.json
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/arrival_kilo.dmm
  _maps/shuttles/cargo_kilo.dmm
  _maps/shuttles/emergency_kilo.dmm
  _maps/shuttles/ferry_kilo.dmm
  _maps/shuttles/labour_kilo.dmm
  _maps/shuttles/mining_kilo.dmm
  code/datums/map_config.dm
  code/datums/shuttles.dm
  code/game/area/Space_Station_13_areas.dm
  icons/turf/areas.dmi
Labels: Map Edit, Revert, Sprites

#171 Gas miners
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Fix, Map Edit

#175 ArcHub Integration
  code/controllers/subsystem/archub.dm
  config/archub_api_key.txt
  tgstation.dme
Labels: Config Update, Feature

#179 make nitryl worth shit in cargo
  code/modules/cargo/exports/large_objects.dm
Labels: Feature

#180 Breakfast now works!
  code/__DEFINES/food.dm
  code/datums/mood_events/needs_events.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/food.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/food_and_drinks/food/snacks_bread.dm
  code/modules/food_and_drinks/food/snacks_egg.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/food/snacks_salad.dm
  code/modules/food_and_drinks/food/snacks_sandwichtoast.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
Labels: Feature

#181 Change to Cold Resistance to Space Adapt
  code/datums/mutations/cold_resistance.dm
Labels: Removal

#182 Heart attacks can happen...
  code/modules/events/heart_attack.dm
Labels: Balance/Rebalance

#183 Removes checks for devourable flags for sec-hounds
  code/game/objects/items/devices/dogborg_sleeper.dm
Labels: Removal, Tweak

#184 port fireman carry
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/datums/components/footstep.dm
  code/datums/components/riding.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob.dm
Labels: Balance/Rebalance, Feature

#185 Kinkmate addition and fix
  modular_citadel/code/game/machinery/vending.dm
  modular_shadow/code/game/machinery/vending.dm
  tgstation.dme
Labels: Feature, Removal, Tweak

#173 Kilostation
  _maps/kilostation.dm
  _maps/kilostation.json
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/shuttles/arrival_kilo.dmm
  _maps/shuttles/cargo_kilo.dmm
  _maps/shuttles/emergency_kilo.dmm
  _maps/shuttles/emergency_syndicate.dmm
  _maps/shuttles/ferry_kilo.dmm
  _maps/shuttles/labour_kilo.dmm
  _maps/shuttles/mining_kilo.dmm
  code/datums/shuttles.dm
  code/game/area/Space_Station_13_areas.dm
  icons/turf/areas.dmi
  tgstation.dme
Labels: Currently Test Merged, Map Edit, Sprites

#187 Botany fancywindows
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Tweak

#189 Removes the antag drafting system
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/game_mode.dm
Labels: Removal, Tweak

#190 Earthblood modification.
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance, Feature

#191 We don't want people knowing that gamemode we're playing on lowpop now, do we?
  code/controllers/subsystem/ticker.dm
  code/game/objects/items/manuals.dm
Labels: Feature, Fix, Tweak

#192 [MIRROR] Fire Cremation
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Feature, Tweak

#193 Incinerator buffs
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Tweak

#199 [s]Removes archub, because it got depreciated and the original PR didn't remove the .dme line.
  code/controllers/subsystem/archub.dm
  config/archub_api_key.txt
  tgstation.dme
Labels: Config Update, Removal

#198 Mindbreaker change
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Tweak

#200 Kilostation QoL
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Feature, Map Edit, Tweak

#202 some bug fixes
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/modules/mob/living/simple_animal/bot/construction.dm
  modular_citadel/icons/mob/muzzled_helmet.dmi
  modular_citadel/icons/mob/suit_digi.dmi
Labels: Fix, Map Edit

#203 Introduces Sigmar's maint bar
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Tweak

#205 3 hour shifts
  code/controllers/subsystem/shuttle.dm
Labels: Tweak

#207 Makes lexorin harder to make
  code/modules/reagents/chemistry/recipes/toxins.dm
Labels: Balance/Rebalance

#209 Changes to crafting.
  code/modules/crafting/recipes.dm
  modular_citadel/code/modules/crafting/recipes.dm
  tgstation.dme
Labels: Code Improvement, Feature, Removal

#208 Ports dynamic gamemode from /vg/ + also normalizes head/antag restrictions
  code/__DEFINES/maths.dm
  code/__HELPERS/roundend.dm
  code/__HELPERS/time.dm
  code/controllers/subsystem/vote.dm
  code/game/gamemodes/brother/traitor_bro.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/dynamic/readme.md
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/overthrow/overthrow.dm
  code/game/gamemodes/revolution/revolution.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  tgstation.dme
Labels: Feature
