Repository ShadowStation/ShadowStation, pull requests merged in 2019-06, with the labels that each got.

#13 Remove suit voucher
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/jobs/job_types/cargo_service.dm
Labels: Balance

#15 Reduce shift time from 6 hrs to 4.
  code/controllers/subsystem/shuttle.dm
Labels: Tweak

#16 more verbose bot relay for bans
  code/modules/admin/NewBan.dm
  code/modules/client/client_procs.dm
Labels: Tweak

#17 Ports new footstep sounds from base /tg/
  code/__DEFINES/footsteps.dm
  code/__DEFINES/is_helpers.dm
  code/datums/components/footstep.dm
  code/game/turfs/open.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor/fancy_floor.dm
  code/game/turfs/simulated/floor/misc_floor.dm
  code/game/turfs/simulated/floor/plating.dm
  code/game/turfs/simulated/floor/plating/asteroid.dm
  code/game/turfs/simulated/floor/plating/dirt.dm
  code/game/turfs/simulated/floor/plating/misc_plating.dm
  code/game/turfs/simulated/floor/reinf_floor.dm
  code/game/turfs/simulated/lava.dm
  code/game/turfs/simulated/water.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  sound/effects/footstep/carpetbarefoot1.ogg
  sound/effects/footstep/carpetbarefoot2.ogg
  sound/effects/footstep/carpetbarefoot3.ogg
  sound/effects/footstep/carpetbarefoot4.ogg
  sound/effects/footstep/carpetbarefoot5.ogg
  sound/effects/footstep/crawl1.ogg
  sound/effects/footstep/hardbarefoot1.ogg
  sound/effects/footstep/hardbarefoot2.ogg
  sound/effects/footstep/hardbarefoot3.ogg
  sound/effects/footstep/hardbarefoot4.ogg
  sound/effects/footstep/hardbarefoot5.ogg
  sound/effects/footstep/hardclaw1.ogg
  sound/effects/footstep/hardclaw2.ogg
  sound/effects/footstep/hardclaw3.ogg
  sound/effects/footstep/hardclaw4.ogg
  sound/effects/footstep/heavy1.ogg
  sound/effects/footstep/heavy2.ogg
  sound/effects/footstep/slime1.ogg
  sound/effects/footstep/woodbarefoot1.ogg
  sound/effects/footstep/woodbarefoot2.ogg
  sound/effects/footstep/woodbarefoot3.ogg
  sound/effects/footstep/woodbarefoot4.ogg
  sound/effects/footstep/woodbarefoot5.ogg
  sound/effects/footstep/woodclaw1.ogg
  sound/effects/footstep/woodclaw2.ogg
  sound/effects/footstep/woodclaw3.ogg
Labels: sound

#18 update travis config
  .travis.yml
  tools/ss13_genchangelog.py
  tools/travis/build_dependencies.sh
  tools/travis/install_build_tools.sh
Labels: Fix

#19 Sprite fixing
  code/modules/surgery/bodyparts/bodyparts.dm
  icons/mob/human_parts_greyscale.dmi
  modular_citadel/icons/mob/mam_markings.dmi
  modular_citadel/icons/mob/markings_notmammals.dmi
  modular_citadel/icons/mob/mutant_bodyparts.dmi
Labels: Feature, Fix, Sprites

#20 Alt ctrl pipes tg
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
Labels: Feature

#21 Ports TG firebots.
  code/__DEFINES/robots.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/extinguisher.dm
  code/modules/crafting/recipes.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  icons/mob/aibots.dmi
  sound/voice/firebot/detected.ogg
  sound/voice/firebot/extinguishing.ogg
  sound/voice/firebot/keepitcool.ogg
  sound/voice/firebot/nofires.ogg
  sound/voice/firebot/onlyyou.ogg
  sound/voice/firebot/stopdropnroll.ogg
  sound/voice/firebot/tempnominal.ogg
  tgstation.dme
Labels: Sound, Sprites

#22 Sloom hnngh
  code/modules/language/slime.dm
  code/modules/surgery/organs/tongue.dm
Labels: Enhancement, Feature

#26 makes the notify command actually work.
  code/modules/admin/chat_commands.dm
Labels: Fix

#27 Item stripping no longer gets interrupted by changes in your actively held item
  code/__HELPERS/mobs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
Labels: Tweak

#28 Fixes atmos and station alert consoles not updating visually
  code/game/machinery/computer/atmos_alert.dm
  code/game/machinery/computer/station_alert.dm
Labels: Fix

#30 actually fixes roundend notifs
  code/modules/admin/chat_commands.dm
Labels: Fix

#31 Tweaks/Buffs hierophant
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
Labels: Tweak

#32 Readds the Clown Car to traitor uplink + Clown Car reworks
  code/modules/uplink/uplink_items.dm
  code/modules/vehicles/cars/clowncar.dm
  code/modules/vehicles/sealed.dm
Labels: Balance/Rebalance, Feature, Fix, Tweak

#34 Engine Revise; DeltaStation
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Currently Test Merged, Map Edit, Tweak

#33 Added toggle-able rainbow lightup shoes and functional heelys to maint loot
  code/_globalvars/lists/maintenance_loot.dm
Labels: Feature

#36 @everyone send help
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Fix

#37 Meteor Sats not exclusive to station goal
  code/modules/cargo/packs.dm
Labels: Tweak

#39 Flight Suits
  code/game/objects/items/tanks/jetpack.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/research/designs/equipment_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/clothing/flightsuit.dmi
Labels: Balance/Rebalance, Currently Test Merged, Feature, Sprites

#41 Map Tweaks: MetaStation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Currently Test Merged, Feature, Map Edit

#42 Ports in the fix against hitting oneself with one's own thrown items.
  code/controllers/subsystem/throwing.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/mob/mob_movement.dm
Labels: Fix

#43 Adds visible balls and multi-breasts
  code/__DEFINES/citadel_defines.dm
  code/__HELPERS/_cit_helpers.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  modular_citadel/code/modules/arousal/arousal.dm
  modular_citadel/code/modules/arousal/organs/breasts.dm
  modular_citadel/code/modules/arousal/organs/eggsack.dm
  modular_citadel/code/modules/arousal/organs/genitals.dm
  modular_citadel/code/modules/arousal/organs/genitals_sprite_accessories.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
  modular_citadel/code/modules/arousal/organs/testicles.dm
  modular_citadel/code/modules/arousal/organs/vagina.dm
  modular_citadel/code/modules/arousal/organs/womb.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_citadel/icons/obj/genitals/breasts.dmi
  modular_citadel/icons/obj/genitals/breasts_onmob.dmi
  modular_citadel/icons/obj/genitals/penis.dmi
  modular_citadel/icons/obj/genitals/testicles.dmi
  modular_citadel/icons/obj/genitals/testicles_onmob.dmi
  modular_citadel/icons/obj/genitals/vagina.dmi
  modular_citadel/icons/obj/genitals/vagina_onmob.dmi
Labels: Feature, Fix

#44 Fixes prosthetic invisible hands, improves female markings
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  modular_citadel/icons/mob/mam_markings.dmi
Labels: Fix

#46 Upstream merge 8493
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
Labels: Fix, Map Edit

#47 [MIRROR] Adds AI core screen selection to character preferences and turns icon selection menu into a radial.
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/silicon.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  icons/mob/AI.dmi
Labels: Fix, Grammar and Formatting, Sprites, Tweak

#48 [MIRROR] Updates radials, makes RCD and RCL use em.
  code/_onclick/hud/radial.dm
  code/_onclick/hud/radial_persistent.dm
  code/datums/action.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/RCL.dm
  code/game/turfs/turf.dm
  code/modules/power/cable.dm
  icons/mob/actions/actions_items.dmi
  icons/mob/radial.dmi
  tgstation.dme
Labels: Code Improvement, Feature, Sprites

#49 [MIRROR] Gives Ninjas back their Weeb speech modification
  code/modules/ninja/suit/mask.dm
Labels: Feature, Upstream PR Merged

#50 [MIRROR] Nerfs Ass Slapping, or how a meme PR made me butthurt, or how I'm now resorting to making degenerate PRs such as this since my permaban from Aurora
  code/__DEFINES/combat.dm
  code/modules/mob/living/carbon/human/species.dm
  icons/effects/effects.dmi
Labels: Balance/Rebalance, Feature, Fix, Sprites, Upstream PR Merged

#54 [MIRROR] fixes pacifism eyestabbing, better this time.
  code/game/objects/items.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/tools/screwdriver.dm
Labels: Fix

#55 [MIRROR] Ports in combat gloves plus.
  code/datums/martial/krav_maga.dm
  code/game/gamemodes/clown_ops/clown_ops.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Upstream PR Merged

#56 [MIRROR] Makes combat gloves look T A C T I C O O L
  code/modules/clothing/gloves/miscellaneous.dm
  icons/obj/clothing/gloves.dmi
Labels: Feature, Sprites, Upstream PR Merged

#59 "@ShadowBot notify" fix
  code/__HELPERS/roundend.dm
Labels: Fix

#58 BoxStation Departure Tweak
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Map Edit
